spring: 
    profiles: 
        active: 
        - dev
        
---
spring: 
    profiles: dev   #开发
    application: 
        name: ioutSourcing-config-dev
        
---
spring: 
    profiles: test  #测试
    application: 
        name: ioutSourcing-config-dev-test